### ISSUE TITLE
Potential for collaboration?

### ISSUE THREAD

**Issue by mackieks** [OrangeFox86/DreamcastControllerUsbPico#120]
Hi! I am the author of [MaplePad](https://github.com/mackieks/MaplePad) which is a Dreamcast controller emulator based on Charlie Cole's Pop'n Music Controller project. It's primarily intended for Dreamcast portable builds, but has also found some modest success as a platform for custom arcade sticks.

Unfortunately MaplePad development has stalled due to my own skill issues and lack of time. The code is very spaghetti (I am not a SWE) but the only _major_ issues are with Windows CE games, due to their rapid Maple commands-- the Maple Bus system I inherited from Charlie's project can't keep up. I noticed you encountered the same issue with your implementation and fixed it last year.

Seeing as how you've pivoted to client-side peripherals, I would love to join forces somehow, or at least trade ideas. While I don't have much to offer your project in terms of clean or reusable code that you don't already have, it would be awesome to potentially bring in your PIO core to patch up MaplePad's final remaining bugs! I'm on discord if you want to talk there (yveltalgriffin)

**Comment by Tails86** [comment]
You've got a cool project there. I have noticed it as I was developing. I think we started around the same time 😆 

Yep, Windows CE was a struggle! I got it to work by holding the line low after write is complete until just before read is activated. Then the internal pull-up resistor is used to more slowly bring the line back high to buy more time. The signal looks a little ugly, but it works. I shot you a friend request.
